### ISSUE TITLE
"Passage", "Center" not excluded from markers on database reset or upload

### ISSUE THREAD

**Issue by j-andrews7** [j-andrews7/strprofiler#21]
What it says on the tin.

**Comment by MikeWLloyd** [comment]
Missed these cases. Thanks for catching that

**Comment by j-andrews7** [comment]
No worries, it was a simple fix. I'm running into a bug where using a custom database on shinyapps.io still seems to reset to the default database, and I really am not sure why as it seems to work fine locally.

**Comment by MikeWLloyd** [comment]
A reactive running haywire and triggering reset? I can look as well to see if I find anything.

**Comment by j-andrews7** [comment]
I'd welcome another set of eyes, I've really got no clue. The app.py file I'm deploying is just:

```python
from strprofiler.app.app import create_app

database = "./tester_db.csv"
create_app(db=database)
```

And the file is just a subset of the main database file. I'm probably about done for the evening anyway, but I think we're pretty close. Once this is figured out, it'll just be updating the docs and the about markdown with relevant details.
