### ISSUE TITLE
CLASTR results with multiple entries for a given line do not display

### ISSUE THREAD

**Issue by j-andrews7** [j-andrews7/strprofiler#25]
Guessing you're aware already, but I've noticed that results from lines with multiple entries do not show up in the single query - [JMAR](https://www.cellosaurus.org/str-search/?name=JMAR&Amelogenin=X&CSF1PO=10,12,13&D13S317=8,11,12&D16S539=8,9,12,13&D5S818=10,12,13&D7S820=9,10,12&TH01=6,8&TPOX=8,10,11&vWA=15,16,18&) is kind of my test "contaminated" sample that would make a good example for the paper.

![image](https://github.com/j-andrews7/strprofiler/assets/10225716/b49a531a-2436-4be7-b616-f35eec87a0f7)

As opposed to the CLASTR site:

![image](https://github.com/j-andrews7/strprofiler/assets/10225716/b7089148-6207-442b-b15e-9279659f1ee3)

**Comment by MikeWLloyd** [comment]
In parsing the results, I used 'best' when multiple results were returned. 

https://github.com/j-andrews7/strprofiler/blob/1bd91a99be750effb4dc609d3bd1d5df26ddeac6/strprofiler/shiny_app/clastr_api.py#L49-L54

We can revisit that choice, but it would need to have the hard coded regex adjusted.

**Comment by j-andrews7** [comment]
Currently, I don't think it returns best or worst, so probably some tinkering needed regardless.

**Comment by MikeWLloyd** [comment]
I left it to report only `profiles_0` in the results object for each returned result. I was thinking that is the top hit. I synonymized that with best in my mind, but I see now that is not correct. I will see about parsing all profiles in each result dict/array combo.

**Comment by MikeWLloyd** [comment]
fix parses both profile 0 and 1, and annotates the result in the table with 'Best' and 'Worst'
