### ISSUE TITLE
Fix "Penta D" and "Penta E" for API POST request

### ISSUE THREAD

**Issue by MikeWLloyd** [j-andrews7/strprofiler#26]
Another thought on this is that currently we have a fix whereby "Penta D" or "Penta_E" are forced to "PentaD", etc. And it seems like it may be better to go the other way, e.g. force "PentaD" or "Penta_E" to "Penta D" and "Penta E" depending on what the API expects. Presumably it requires `%20` as the space in the URL for those markers.

_Originally posted by @j-andrews7 in https://github.com/j-andrews7/strprofiler/issues/24#issuecomment-2110764488_

**Comment by j-andrews7** [comment]
Went ahead and threw "Penta C" into the mix as well since it's also an option on the CLASTR site (though I've never seen it). 

Also added the swap functionality to the `_pentafix` function with a new `reverse` parameter just to try to keep things tidy, also has the added side effect of making it easier to apply to the batch queries. Though those don't seem to be returning any matching results for me currently.

**Comment by MikeWLloyd** [comment]
Thanks for doing that, it is much cleaner this way. I will check what is going on with the batch function. I'm about to push a modal warning for non-valid marker names.

**Comment by MikeWLloyd** [comment]
> ...Though those don't seem to be returning any matching results for me currently.

Just double checking, what is your `Similarity Score Filter Threshold` on the single query page? 

I don't have the batch query filter linked to the options on the batch query page yet, and am borrowing the single query options. It is the next thing on my list is to add correct options for the batch API query. The API can only accept a single similarity algorithm, so the batch UI options needs to be adjusted.

**Comment by j-andrews7** [comment]
Ah, yeah, that would be it, good thinking. Can probably stick the inputs in conditional panels - the current setup for when the STRprofiler DB is used, and then one for when CLASTR is chosen to have a dropdown for the algorithm and a single textbox for the threshold.

**Comment by MikeWLloyd** [comment]
I fixed the conditional batch inputs in 815036f.
