### ISSUE TITLE
App: long running tasks blockers

### ISSUE THREAD

**Issue by MikeWLloyd** [j-andrews7/strprofiler#27]
Long running query (or other tasks) block reactivity for concurrent users on the same server. Non-blocking `async` calls are needed to overcome this. Implementation of those presents architecture issues for how functions are currently called. See https://shiny.posit.co/py/docs/nonblocking.html#true-non-blocking-behavior-with-extendedtask

**Comment by j-andrews7** [comment]
Depending on hosting & load management settings, this shouldn't _really_ be an issue for an app like this, as the server should [spin up additional instances/workers to scale with the number of users](https://shiny.posit.co/r/articles/improve/scaling-and-tuning/):

![image](https://github.com/j-andrews7/strprofiler/assets/10225716/517a6ef3-fba4-4d06-8253-9a44f0cbf916)

We don't really have any long-running computations being performed where I'd expect the concurrency to really be noticeably affected.

This isn't to discourage implementation, just that is may be unnecessary. And in the past, I've found it non-trivial to implement (in R, which is a bit of a different beast).

**Comment by MikeWLloyd** [comment]
non-trivial is the key word. I spent a time seeing how to accomplish this, and hit some pretty serious walls. For now, I think you are right we don't need to concerns ourselves with it. I do know that docker / cloud implementations can struggle with load balance. I will close this for now, and we can always revisit in the future.
