### ISSUE TITLE
Add CI via Github actions once tests are written.

### ISSUE THREAD

**Issue by j-andrews7** [j-andrews7/strprofiler#3]
https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

**Comment by sculley** [comment]
Hey, can you assign this to me, I assume this can be completed before adding the required tests i.e. the action will just pass as no tests to complete?

**Comment by j-andrews7** [comment]
Sure, and yeah, that should be the case. Should pretty much just be the
template in the link I think.

**Comment by sculley** [comment]
I will start this later today :+1:
