### ISSUE TITLE
Error message when CLASTR returns no results is unhelpful

### ISSUE THREAD

**Issue by j-andrews7** [j-andrews7/strprofiler#30]
Makes it seem as though something is wrong with the query or return:

![image](https://github.com/user-attachments/assets/e275ba60-b9dc-4e80-ade3-0815e49fa2c9)

Need to catch this case and return a more helpful error message.

We supposedly already catch this, but clearly it's not formatted quite the way we thought...though I don't remember this problem previously, so it may have been a more recent change in the API.

Regardless, issue is likely at either https://github.com/j-andrews7/STRprofiler/blob/main/strprofiler/shiny_app/shiny_app.py#L770 or https://github.com/j-andrews7/STRprofiler/blob/main/strprofiler/shiny_app/clastr_api.py#L64 and can be fixed in one of those locations.

**Comment by MikeWLloyd** [comment]
Current returns for empty results: 

```
Empty DataFrame
Columns: [No Clastr Result]
Index: []
```

Logic check: for empty results 

```
if ("No CLASTR Result" in out_df.columns) | ("Error" in out_df.columns):
```


`Clastr` != `CLASTR`. It will be a simple fix to correct the logic here.

**Comment by j-andrews7** [comment]
Will push a new version this weekend.
